export const questions = [
	{
		id: 1,
		question: "What is the capital of India?",
		options: ["Delhi", "Mumbai", "Kolkata", "Chennai"],
		correctAnswer: "Delhi",
	},
	{
		id: 2,
		question: "What is the capital of Australia?",
		options: ["Sydney", "Melbourne", "Canberra", "Perth"],
		correctAnswer: "Canberra",
	},
	{
		id: 3,
		question: "What is the capital of United States?",
		options: ["Washington DC", "New York", "Los Angeles", "Chicago"],
		correctAnswer: "Washington DC",
	},
	{
		id: 4,
		question: "What is the capital of United Kingdom?",
		options: ["London", "Manchester", "Liverpool", "Birmingham"],
		correctAnswer: "London",
	},
	{
		id: 5,
		question: "What is the capital of China?",
		options: ["Shanghai", "Beijing", "Shenzhen", "Guangzhou"],
		correctAnswer: "Beijing",
	},
	{
		id: 6,
		question: "What is the capital of Japan?",
		options: ["Tokyo", "Osaka", "Kyoto", "Yokohama"],
		correctAnswer: "Tokyo",
	},
	{
		id: 7,
		question: "What is the capital of Canada?",
		options: ["Toronto", "Montreal", "Vancouver", "Ottawa"],
		correctAnswer: "Ottawa",
	},
	{
		id: 8,
		question: "What is the capital of Brazil?",
		options: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"],
		correctAnswer: "Brasilia",
	},
	{
		id: 9,
		question: "What is the capital of Russia?",
		options: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
		correctAnswer: "Moscow",
	},
	{
		id: 10,
		question: "What is the capital of South Korea?",
		options: ["Seoul", "Busan", "Incheon", "Daegu"],
		correctAnswer: "Seoul",
	},
	{
		id: 11,
		question: "What is the capital of Germany?",
		options: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
		correctAnswer: "Berlin",
	},
	{
		id: 12,
		question: "What is the capital of France?",
		options: ["Paris", "Marseille", "Lyon", "Toulouse"],
		correctAnswer: "Paris",
	},
	{
		id: 13,
		question: "What is the capital of Italy?",
		options: ["Rome", "Milan", "Naples", "Turin"],
		correctAnswer: "Rome",
	},
	{
		id: 14,
		question: "What is the capital of Spain?",
		options: ["Madrid", "Barcelona", "Valencia", "Seville"],
		correctAnswer: "Madrid",
	},
	{
		id: 15,
		question: "What is the capital of Mexico?",
		options: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"],
		correctAnswer: "Mexico City",
	},
	{
		id: 16,
		question: "What is the capital of Argentina?",
		options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"],
		correctAnswer: "Buenos Aires",
	},
	{
		id: 17,
		question: "What is the capital of South Africa?",
		options: ["Cape Town", "Johannesburg", "Durban", "Pretoria"],
		correctAnswer: "Pretoria",
	},
	{
		id: 18,
		question: "What is the capital of Nigeria?",
		options: ["Lagos", "Kano", "Ibadan", "Abuja"],
		correctAnswer: "Abuja",
	},
	{
		id: 19,
		question: "What is the capital of Egypt?",
		options: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima"],
		correctAnswer: "Cairo",
	},
	{
		id: 20,
		question: "What is the capital of Indonesia?",
		options: ["Jakarta", "Surabaya", "Medan", "Bandung"],
		correctAnswer: "Jakarta",
	},
];
